language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - cd ..
  - django-admin.py startproject --template=./django-template --extension=py,md my_proj
  - cd my_proj/src
  - cp my_proj/settings/local.sample.env my_proj/settings/local.env
  - python manage.py migrate
