apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ project_name }}-server-rc
spec:
  replicas: 1
  selector:
    app: {{ project_name }}-server
  template:
    metadata:
      labels:
        app: {{ project_name }}-server
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: {{ project_name }}-server
        image: lucemia/{{ project_name }}:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

